/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

import { MockQueryBuilder } from "./mock-db";

export class MockSupabaseClient {
  auth = {
    async getUser() {
      if (typeof window === "undefined") {
        return {
          data: { user: { id: "mock-user-123", email: "contact@bistrotdeshalles.fr" } },
          error: null,
        };
      }
      const loggedOut = localStorage.getItem("tf_logged_out") === "true";
      if (loggedOut) {
        return { data: { user: null }, error: new Error("Logged out") };
      }
      const userStr =
        localStorage.getItem("tf_user") ||
        JSON.stringify({ id: "mock-user-123", email: "contact@bistrotdeshalles.fr" });
      return { data: { user: JSON.parse(userStr) }, error: null };
    },

    async getSession() {
      if (typeof window === "undefined") {
        return {
          data: {
            session: {
              access_token: "mock-token-123",
              user: { id: "mock-user-123", email: "contact@bistrotdeshalles.fr" },
            },
          },
          error: null,
        };
      }
      const loggedOut = localStorage.getItem("tf_logged_out") === "true";
      if (loggedOut) {
        return { data: { session: null }, error: null };
      }
      const userStr =
        localStorage.getItem("tf_user") ||
        JSON.stringify({ id: "mock-user-123", email: "contact@bistrotdeshalles.fr" });
      return {
        data: {
          session: {
            access_token: "mock-token-123",
            user: JSON.parse(userStr),
          },
        },
        error: null,
      };
    },

    async signUp({ email }: { email: string }) {
      if (typeof window !== "undefined") {
        localStorage.removeItem("tf_logged_out");
        const u = { id: "mock-user-123", email };
        localStorage.setItem("tf_user", JSON.stringify(u));
        this._notify("SIGNED_IN", { user: u });
      }
      return { data: { user: { id: "mock-user-123", email } }, error: null };
    },

    async signInWithPassword({ email }: { email: string }) {
      if (typeof window !== "undefined") {
        localStorage.removeItem("tf_logged_out");
        const u = { id: "mock-user-123", email };
        localStorage.setItem("tf_user", JSON.stringify(u));
        this._notify("SIGNED_IN", { user: u });
      }
      return { data: { user: { id: "mock-user-123", email } }, error: null };
    },

    async signOut() {
      if (typeof window !== "undefined") {
        localStorage.setItem("tf_logged_out", "true");
        localStorage.removeItem("tf_user");
        this._notify("SIGNED_OUT", null);
      }
      return { error: null };
    },

    _callbacks: [] as any[],
    onAuthStateChange(callback: any) {
      this._callbacks.push(callback);
      this.getSession().then(({ data }) => {
        if (this._callbacks.includes(callback)) {
          callback(data?.session ? "SIGNED_IN" : "SIGNED_OUT", data?.session);
        }
      });
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              this._callbacks = this._callbacks.filter((cb) => cb !== callback);
            },
          },
        },
      };
    },

    _notify(event: any, session: any) {
      for (const cb of this._callbacks) {
        cb(event, session);
      }
    },

    async setSession(tokens: any) {
      if (typeof window !== "undefined") {
        localStorage.removeItem("tf_logged_out");
        localStorage.setItem(
          "tf_user",
          JSON.stringify(
            tokens.user || { id: "mock-user-123", email: "contact@bistrotdeshalles.fr" },
          ),
        );
      }
      return { data: { session: tokens }, error: null };
    },

    async getClaims(token: string) {
      return {
        data: {
          claims: {
            sub: "mock-user-123",
            email: "contact@bistrotdeshalles.fr",
          },
        },
        error: null,
      };
    },
  };

  from(table: string) {
    return new MockQueryBuilder(table);
  }

  channel(channelName: string) {
    return {
      on(event: string, filter: any, callback: any) {
        return this;
      },
      subscribe(callback?: any) {
        if (callback) callback("SUBSCRIBED");
        return this;
      },
    };
  }

  async removeChannel(channel: any) {
    return { error: null };
  }

  storage = {
    from(bucket: string) {
      return {
        async upload(path: string, file: File, options?: any) {
          const url =
            typeof window !== "undefined"
              ? URL.createObjectURL(file)
              : "https://images.unsplash.com/photo-1544025162-d76694265947";
          return { data: { path, url }, error: null };
        },
        async createSignedUrl(path: string, ttl: number) {
          return {
            data: { signedUrl: "https://images.unsplash.com/photo-1544025162-d76694265947" },
            error: null,
          };
        },
      };
    },
  };
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.info(
      "[Supabase] Environment variables missing. Using fully featured MockSupabaseClient.",
    );
    return new MockSupabaseClient() as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
